#!/bin/bash

# Gets the name of this script and adds a .py extension:
APPNAME=${0##*/}.py
# Gets current folder:
PWD=$(exec pwd)

ARGS=${@}
NARGS=$#
echo "Current folder: $PWD"
echo "Script name with added extension: $APPNAME"
echo "Number of arguments: $NARGS"
echo "Arguments: $ARGS"
#python $PWD/$APPNAME


